doctrine:
  orm:
    dql:
      datetime_functions:
        month: DoctrineExtensions\Query\Mysql\Month
        year: DoctrineExtensions\Query\Mysql\Year
    mappings:
      AcMarche\Duobac:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/AcMarche/Duobac/src/Entity'
        prefix: 'AcMarche\Duobac'
        alias: AcMarche\Duobac
